### PR TITLE
fix: use global DFL

### LINKED ISSUE #28: HTLB for Deck Not Working with Decky Loader 2.10.15-pre2
Steam OS 3.5.15 preview update broke Decky Loader 2.10.14. Decky Loader was updated to 2.10.15-pre2 and sadly the HLTB plugin no longer works.

### LINKED ISSUE #30: Decky loader is now 2.11.1-pre1 and HLTB is not working
Error says Cannot read properties of undefined...

Sorry that's all I see on the notification

### LINKED ISSUE #31: TypeError: Cannot read properties of undefined (reading'SimpleModal')
getting this error upon booting on new steam os update, on the latest stable releases of steam os and decky loader

### PR DESCRIPTION
**Pull request by foosel**
Fixes issue with latest SteamDeck Client.

Compare to mcarlucci/decky-storage-cleaner#10

Closes #28
Closes #30
Closes #31

I've built a test release 1.4.2 on my fork and successfully tested it through manual install on SteamOS 3.5.17

### CODE REVIEW

**Review by HirschBerge — APPROVED** [review]

**Comment by 5310** [comment]
Just in case it comes to it, would it be possible for you to put up your fork on the Decky "store"?

**Comment by Majkysek** [comment]
How do I switch the GFL and where?

**Comment by foosel** [comment]
> Just in case it comes to it, would it be possible for you to put up your fork on the Decky "store"?

Given that I already have my hands full with maintaining other open source stuff, and have no experience at all with Decky plugin development, I don't think I should be doing that. 

I hope the maintainer @hulkrelax will soon see this and merge it, or alternatively someone with more experience and available time than me will step up to continue maintenance.

Until then: Enable developer mode in Decky and install my 1.4.2 build via the URL `https://github.com/foosel/hltb-for-deck/releases/download/v1.4.2/hltb-for-deck.zip` - and then ignore the update prompt that would downgrade it back to the official 1.4.1.

**Review by JohnDoe-404 — APPROVED** [review]

**Review by JohnDoe-404 — APPROVED** [review]
Good

**Review by JohnDoe-404 — APPROVED** [review]

**Review by gatesphere — APPROVED** [review]

**Review by v3lasco — APPROVED** [review]

**Review by GhilesA — APPROVED** [review]

**Comment by foosel** [comment]
For the record, all of you approving this pull request won't help move this forward, only a reaction and hopefully a merge by @hulkrelax will 😅

**Comment by foosel** [comment]
Apparently @safijari has now taken over maintenance and this is no longer needed. Closing.

https://github.com/safijari/hltb-for-deck

**Pull request closed without merging**
